languageCode = "en-us"
title = "OpenAerialMap Documentation"
theme = "book"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    BookRepo = "https://github.com/hotosm/oam-docs-hugo"
    BookShowToC = false
    BookEditPath = "/edit/master/content/"
    matomoSiteID = 23

[imaging]
    resampleFilter = "box"
    quality = 75