languageCode = "en-us"
title = "OpenAerialMap Docs"
theme = "hotdocs"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    DefaultContentLanguage = "en"
    GithubRepo = "https://github.com/hotosm/oam-docs-hugo"
    SiteURL = "https://docs.openaerialmap.org"
    matomoSiteID = 23

[imaging]
    resampleFilter = "box"
    quality = 75

[languages]
#   [languages.fr]
#    contentDir = "content/fr"
#    languageName = "Français"
#    weight = 10
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 20
